name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key
          cat >> ~/.ssh/config <<EOF
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          EOF
          # Debug output
          echo "SSH config:"
          cat ~/.ssh/config
          echo "Private key head:"
          head -n 3 ~/.ssh/deploy-key.pem
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Test SSH connection
        run: ssh -v my-vps "echo 'Successfully connected!'"

      - name: Print project root directory
        run: ssh my-vps "pwd && cd ${{ secrets.PROJECT_ROOT }} && pwd"
